// ============================================================================
// Catálogo de aplicaciones de baterías Duncan
// Transcrito del PDF oficial. Estructura por fila:
//   { marca, modelo, anioDesde, anioHasta, grupo: [opciones], cp: opcional }
// "grupo" son las opciones de batería recomendadas; "cp" es la opción CP.
// categoria: 'auto' | 'autobus' | 'camion'
// ============================================================================

export interface AplicacionBateria {
  marca: string;
  modelo: string;
  anio_desde: string;
  anio_hasta: string;
  grupo: string[]; // una o dos opciones de batería
  cp?: string;
  categoria: "auto" | "autobus" | "camion";
}

export const BATERIAS: AplicacionBateria[] = [
  // ===================== AUTOMÓVILES =====================
  // --- NISSAN ---
  { marca: "NISSAN", modelo: "MONTERO PAJERO", anio_desde: "14", anio_hasta: "21", grupo: ["27R - 1100", "24R - 1150"], cp: "27Q - 1200", categoria: "auto" },
  { marca: "NISSAN", modelo: "OUTLANDER", anio_desde: "07", anio_hasta: "10", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "NISSAN", modelo: "ALMERA", anio_desde: "98", anio_hasta: "10", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "NISSAN", modelo: "ALTIMA / MÁXIMA / MURANO", anio_desde: "98", anio_hasta: "08", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "NISSAN", modelo: "ARMADA / PATROL", anio_desde: "08", anio_hasta: "09", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "NISSAN", modelo: "FRONTIER", anio_desde: "05", anio_hasta: "12", grupo: ["34R - 1000"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "NISSAN", modelo: "PATHFINDER", anio_desde: "93", anio_hasta: "97", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "NISSAN", modelo: "PATHFINDER", anio_desde: "01", anio_hasta: "02", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "NISSAN", modelo: "SENTRA", anio_desde: "91", anio_hasta: "07", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "NISSAN", modelo: "TERRANO", anio_desde: "02", anio_hasta: "03", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "NISSAN", modelo: "TIIDA", anio_desde: "07", anio_hasta: "08", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },
  { marca: "NISSAN", modelo: "X-SALON", anio_desde: "91", anio_hasta: "98", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "NISSAN", modelo: "X-TRAIL", anio_desde: "05", anio_hasta: "", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "NISSAN", modelo: "X-TRAIL", anio_desde: "06", anio_hasta: "", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },

  // --- PEUGEOT ---
  { marca: "PEUGEOT", modelo: "206 / 207 / 306 / 307 / 407", anio_desde: "06", anio_hasta: "14", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "PEUGEOT", modelo: "PARTNER", anio_desde: "11", anio_hasta: "12", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "PEUGEOT", modelo: "405 / 605", anio_desde: "92", anio_hasta: "96", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },

  // --- RENAULT ---
  { marca: "RENAULT", modelo: "CLIO / KANGOO / EXPRESS", anio_desde: "92", anio_hasta: "08", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "RENAULT", modelo: "DUSTER", anio_desde: "13", anio_hasta: "15", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "RENAULT", modelo: "FUEGO / GALA", anio_desde: "92", anio_hasta: "08", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "RENAULT", modelo: "LAGUNA", anio_desde: "94", anio_hasta: "15", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "RENAULT", modelo: "LOGAN", anio_desde: "06", anio_hasta: "09", grupo: ["43R - 800", "36R - 750"], categoria: "auto" },
  { marca: "RENAULT", modelo: "MEGANE II / R-19 / R-21", anio_desde: "06", anio_hasta: "09", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "RENAULT", modelo: "R-30", anio_desde: "80", anio_hasta: "82", grupo: ["24 - 1150", "24 - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "RENAULT", modelo: "SANDERO", anio_desde: "12", anio_hasta: "16", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "RENAULT", modelo: "SCENIC / SYMBOL / TRAFFIC / TWINGO", anio_desde: "99", anio_hasta: "09", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "RENAULT", modelo: "SANDERO / STEPWAY / LOGAN", anio_desde: "24", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },

  // --- ROVER ---
  { marca: "ROVER", modelo: "MINICORD", anio_desde: "91", anio_hasta: "95", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },

  // --- SEAT ---
  { marca: "SEAT", modelo: "CORDOBA / IBIZA / LEON / TOLEDO", anio_desde: "00", anio_hasta: "08", grupo: ["36R - 750"], categoria: "auto" },

  // --- SUBARU ---
  { marca: "SUBARU", modelo: "FORESTER / LEGACY", anio_desde: "98", anio_hasta: "01", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "SUBARU", modelo: "IMPREZA", anio_desde: "96", anio_hasta: "01", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },

  // --- SUZUKI ---
  { marca: "SUZUKI", modelo: "GRAND VITARA", anio_desde: "00", anio_hasta: "08", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "SUZUKI", modelo: "SIDEKICK", anio_desde: "92", anio_hasta: "94", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },

  // --- TATA ---
  { marca: "TATA", modelo: "INDICA / INDIGO", anio_desde: "07", anio_hasta: "11", grupo: ["36R - 750"], categoria: "auto" },

  // --- TOYOTA (pág 1) ---
  { marca: "TOYOTA", modelo: "4-RUNNER / FJ 40 / AUTANA / CAMRY", anio_desde: "93", anio_hasta: "19", grupo: ["24R - 1150", "24R - 900"], cp: "27Q - 1200", categoria: "auto" },
  { marca: "TOYOTA", modelo: "4-RUNNER SR5 / LIMITED", anio_desde: "22", anio_hasta: "", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "TOYOTA", modelo: "CELICA", anio_desde: "92", anio_hasta: "99", grupo: ["45R - 850", "45R - 750"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "CELICA", anio_desde: "00", anio_hasta: "01", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "COASTER", anio_desde: "01", anio_hasta: "14", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "COROLLA / SKY", anio_desde: "86", anio_hasta: "02", grupo: ["45R - 850", "45R - 750"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "COROLLA", anio_desde: "03", anio_hasta: "08", grupo: ["NS40R - 670", "45R - 750"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "COROLLA", anio_desde: "09", anio_hasta: "15", grupo: ["45R - 850", "45R - 750"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "COROLLA", anio_desde: "16", anio_hasta: "", grupo: ["Según muestra"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "COROLLA CROSS", anio_desde: "22", anio_hasta: "", grupo: ["48R - 1200"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "CROWN", anio_desde: "92", anio_hasta: "03", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "TOYOTA", modelo: "FJ-40 (MACHO) / HIACE", anio_desde: "70", anio_hasta: "00", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "FORTUNER", anio_desde: "05", anio_hasta: "17", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "TOYOTA", modelo: "FORTUNER DUBAI (IMP) / HILUX DUBAI (IMP)", anio_desde: "17", anio_hasta: "", grupo: ["48R - 1200"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "KAVAK", anio_desde: "06", anio_hasta: "18", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "TOYOTA", modelo: "HILUX", anio_desde: "92", anio_hasta: "98", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "HILUX 4 CIL", anio_desde: "99", anio_hasta: "14", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "HILUX 6 CIL / MERÚ / TUNDRA", anio_desde: "99", anio_hasta: "15", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "TOYOTA", modelo: "HILUX", anio_desde: "19", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },

  // --- TOYOTA (pág 2) ---
  { marca: "TOYOTA", modelo: "LAND CRUISER", anio_desde: "70", anio_hasta: "93", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "LAND CRUISER", anio_desde: "06", anio_hasta: "17", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "TOYOTA", modelo: "LAND CRUISER LC 200", anio_desde: "21", anio_hasta: "22", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "TOYOTA", modelo: "LAND CRUISER LC 300", anio_desde: "21", anio_hasta: "22", grupo: ["48R - 1200"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "TOYOTA", modelo: "LAND CRUISER 76LX / 79 / 300 VX / PRADO", anio_desde: "22", anio_hasta: "", grupo: ["27R - 1100"], cp: "27Q - 1200", categoria: "auto" },
  { marca: "TOYOTA", modelo: "PASEO / RAV-4", anio_desde: "93", anio_hasta: "16", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "PRADO / PREVIA / SIENNA", anio_desde: "01", anio_hasta: "16", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "TOYOTA", modelo: "RORAIMA", anio_desde: "01", anio_hasta: "10", grupo: ["24R - 1150", "24R - 900"], cp: "27Q - 1200", categoria: "auto" },
  { marca: "TOYOTA", modelo: "SAMURAI", anio_desde: "01", anio_hasta: "10", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "STARLET", anio_desde: "92", anio_hasta: "00", grupo: ["45 - 750"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "STATION WAGON", anio_desde: "70", anio_hasta: "98", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "STATION WAGON", anio_desde: "99", anio_hasta: "07", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "TOYOTA", modelo: "TERCEL", anio_desde: "91", anio_hasta: "98", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "TERIOS", anio_desde: "03", anio_hasta: "05", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "TERIOS", anio_desde: "06", anio_hasta: "15", grupo: ["N40R - 700"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "YARIS", anio_desde: "00", anio_hasta: "05", grupo: ["45 - 750"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "YARIS / YARIS BELTA / YARIS SPORT", anio_desde: "06", anio_hasta: "16", grupo: ["N40R - 700"], categoria: "auto" },
  { marca: "TOYOTA", modelo: "YARIS CROSS", anio_desde: "24", anio_hasta: "", grupo: ["NS40R - 670"], categoria: "auto" },

  // --- VENIRAUTO ---
  { marca: "VENIRAUTO", modelo: "CENTAURO / SAMANA", anio_desde: "06", anio_hasta: "16", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "VENIRAUTO", modelo: "TURPIAL / SAIPA", anio_desde: "06", anio_hasta: "15", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "VENIRAUTO", modelo: "SAINA", anio_desde: "23", anio_hasta: "", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "VENIRAUTO", modelo: "QUICK", anio_desde: "23", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },

  // --- VENUCIA ---
  { marca: "VENUCIA", modelo: "TERRALORD", anio_desde: "24", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },
  { marca: "VENUCIA", modelo: "V-ONLINE", anio_desde: "24", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },

  // --- VOLKSWAGEN ---
  { marca: "VOLKSWAGEN", modelo: "GOLF / GOL", anio_desde: "96", anio_hasta: "08", grupo: ["43R - 800", "36R - 750"], categoria: "auto" },
  { marca: "VOLKSWAGEN", modelo: "JETTA / PASSAT / VENTO / BORA", anio_desde: "96", anio_hasta: "08", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "VOLKSWAGEN", modelo: "ESCARABAJO", anio_desde: "70", anio_hasta: "03", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "VOLKSWAGEN", modelo: "CROSS FOX / FOX / SPACE FOX", anio_desde: "05", anio_hasta: "13", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "VOLKSWAGEN", modelo: "NEW BEATTLE / POLO", anio_desde: "00", anio_hasta: "13", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "VOLKSWAGEN", modelo: "TOUAREG", anio_desde: "05", anio_hasta: "08", grupo: ["49R - 1300"], categoria: "auto" },

  // --- VOLVO ---
  { marca: "VOLVO", modelo: "740 / 94", anio_desde: "90", anio_hasta: "92", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },

  // --- ZOTYE ---
  { marca: "ZOTYE", modelo: "NÓMADA", anio_desde: "07", anio_hasta: "10", grupo: ["45R - 750"], categoria: "auto" },
  { marca: "ZOTYE", modelo: "VISTA / MANZA", anio_desde: "12", anio_hasta: "14", grupo: ["36R - 750"], categoria: "auto" },

  // --- ZX AUTO ---
  { marca: "ZX AUTO", modelo: "ZX", anio_desde: "24", anio_hasta: "", grupo: ["42R - 850", "43R - 800"], categoria: "auto" },

  // ===================== AUTOBUSES (pág 2) =====================
  { marca: "BLUE-BIRD", modelo: "TODOS", anio_desde: "00", anio_hasta: "10", grupo: ["4D - 1500"], categoria: "autobus" },
  { marca: "CHEVROLET", modelo: "TODOS", anio_desde: "56", anio_hasta: "00", grupo: ["24 - 1150", "24 - 900"], cp: "27Q - 1200", categoria: "autobus" },
  { marca: "CHEVROLET", modelo: "NPR TURBO (2 bat)", anio_desde: "10", anio_hasta: "11", grupo: ["27R - 1100"], cp: "27Q - 1200", categoria: "autobus" },
  { marca: "ENCAVA", modelo: "36 PUESTOS", anio_desde: "67", anio_hasta: "95", grupo: ["8D - 1700"], categoria: "autobus" },
  { marca: "ENCAVA", modelo: "24 PUESTOS", anio_desde: "67", anio_hasta: "95", grupo: ["4D - 1500"], categoria: "autobus" },
  { marca: "FORD", modelo: "TODOS", anio_desde: "56", anio_hasta: "00", grupo: ["24 - 1150", "24 - 900"], categoria: "autobus" },
  { marca: "MERCEDES BENZ", modelo: "MB 303", anio_desde: "74", anio_hasta: "92", grupo: ["31 - 1250"], categoria: "autobus" },
  { marca: "PEGASO", modelo: "TODOS", anio_desde: "78", anio_hasta: "95", grupo: ["4D - 1500"], categoria: "autobus" },
  { marca: "RENAULT", modelo: "TODOS", anio_desde: "89", anio_hasta: "99", grupo: ["4D - 1500"], categoria: "autobus" },
  { marca: "YUTONG", modelo: "TODOS", anio_desde: "08", anio_hasta: "18", grupo: ["4D - 1500"], categoria: "autobus" },

  // ===================== CAMIONES (pág 3) =====================
  { marca: "CHEVROLET", modelo: "C10 / C60 / C70 / C-3500", anio_desde: "56", anio_hasta: "99", grupo: ["24 - 1150", "24 - 900"], categoria: "camion" },
  { marca: "CHEVROLET", modelo: "C-3500", anio_desde: "00", anio_hasta: "05", grupo: ["78 - 850", "34 - 1000"], categoria: "camion" },
  { marca: "CHEVROLET", modelo: "C-3500", anio_desde: "11", anio_hasta: "15", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "camion" },
  { marca: "CHEVROLET", modelo: "EXZ / EXR", anio_desde: "08", anio_hasta: "15", grupo: ["4D - 1500"], categoria: "camion" },
  { marca: "CHEVROLET", modelo: "FVR (2 bat) / FSR (2 bat)", anio_desde: "06", anio_hasta: "11", grupo: ["30H - 1250"], categoria: "camion" },
  { marca: "CHEVROLET", modelo: "FSR", anio_desde: "14", anio_hasta: "", grupo: ["4D - 1500"], categoria: "camion" },
  { marca: "CHEVROLET", modelo: "KODIAK 229", anio_desde: "92", anio_hasta: "10", grupo: ["27R - 1100"], categoria: "camion" },
  { marca: "CHEVROLET", modelo: "KODIAK 157 / 175", anio_desde: "02", anio_hasta: "10", grupo: ["30H - 1250"], categoria: "camion" },
  { marca: "CHEVROLET", modelo: "NPR / NKR / NHR", anio_desde: "92", anio_hasta: "15", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "camion" },
  { marca: "CHEVROLET", modelo: "NLR", anio_desde: "14", anio_hasta: "", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "camion" },
  { marca: "CHEVROLET", modelo: "NPR TURBO", anio_desde: "10", anio_hasta: "15", grupo: ["27R - 1100"], cp: "27Q - 1200", categoria: "camion" },
  { marca: "CHEVROLET", modelo: "SUPER BRIGADIER", anio_desde: "98", anio_hasta: "00", grupo: ["31 - 1250"], categoria: "camion" },
  { marca: "DONGFENG", modelo: "DUOLIKA / XIAOBA / JIMBA", anio_desde: "12", anio_hasta: "15", grupo: ["49R - 1300"], categoria: "camion" },
  { marca: "DONGFENG", modelo: "ZNA PICK UP", anio_desde: "13", anio_hasta: "", grupo: ["22R - 850"], categoria: "camion" },
  { marca: "FORD", modelo: "CARGO 815", anio_desde: "03", anio_hasta: "15", grupo: ["30H - 1250"], categoria: "camion" },
  { marca: "FORD", modelo: "CARGO 1721", anio_desde: "04", anio_hasta: "08", grupo: ["4DLT - 1450"], categoria: "camion" },
  { marca: "FORD", modelo: "CARGO 1721", anio_desde: "08", anio_hasta: "15", grupo: ["4D - 1500"], categoria: "camion" },
  { marca: "FORD", modelo: "CHANA", anio_desde: "89", anio_hasta: "98", grupo: ["45 - 750"], categoria: "camion" },
  { marca: "FORD", modelo: "CARGO 2632 / 4432 / 4532", anio_desde: "02", anio_hasta: "08", grupo: ["8D - 1700"], categoria: "camion" },
  { marca: "FORD", modelo: "F 350", anio_desde: "56", anio_hasta: "99", grupo: ["24 - 1150", "24 - 900"], categoria: "camion" },
  { marca: "FORD", modelo: "F 350 (TRITON)", anio_desde: "00", anio_hasta: "10", grupo: ["59 - 850"], categoria: "camion" },
  { marca: "FORD", modelo: "F 350 (SUPER DUTY)", anio_desde: "11", anio_hasta: "14", grupo: ["65 - 1100"], categoria: "camion" },
  { marca: "FORD", modelo: "F 7000 / 8000", anio_desde: "00", anio_hasta: "01", grupo: ["31 - 1250"], categoria: "camion" },
  { marca: "FREIGHTLINER", modelo: "COLUMBIA CL / M2-106", anio_desde: "00", anio_hasta: "10", grupo: ["31 - 1250"], categoria: "camion" },
  { marca: "FREIGHTLINER", modelo: "112", anio_desde: "00", anio_hasta: "10", grupo: ["31 - 1250"], categoria: "camion" },
  { marca: "HINO", modelo: "BUS", anio_desde: "12", anio_hasta: "17", grupo: ["27R - 1100"], cp: "27Q - 1200", categoria: "camion" },
  { marca: "INTERNATIONAL", modelo: "TODOS", anio_desde: "00", anio_hasta: "10", grupo: ["31 - 1250"], categoria: "camion" },
  { marca: "IVECO", modelo: "DAILY LIVIANOS", anio_desde: "98", anio_hasta: "11", grupo: ["49R - 1300"], categoria: "camion" },
  { marca: "IVECO", modelo: "DAILY GNV / ESCUDO", anio_desde: "11", anio_hasta: "12", grupo: ["27R - 1100"], categoria: "camion" },
  { marca: "IVECO", modelo: "EURO CARGO", anio_desde: "89", anio_hasta: "11", grupo: ["30H - 1250"], categoria: "camion" },
  { marca: "IVECO", modelo: "EURO CARGO / TECTOR / VERTIS", anio_desde: "12", anio_hasta: "16", grupo: ["27R - 1100"], categoria: "camion" },
  { marca: "IVECO", modelo: "TECTOR / EURO TECTOR", anio_desde: "98", anio_hasta: "11", grupo: ["30H - 1250"], categoria: "camion" },
  { marca: "IVECO", modelo: "EUROTRACKER / STRALIS", anio_desde: "83", anio_hasta: "11", grupo: ["4DLT - 1450"], categoria: "camion" },
  { marca: "IVECO", modelo: "NEW STRALIS", anio_desde: "83", anio_hasta: "11", grupo: ["4DLT - 1450"], categoria: "camion" },
  { marca: "IVECO", modelo: "POWER DAILY", anio_desde: "12", anio_hasta: "16", grupo: ["49R - 1300"], categoria: "camion" },
  { marca: "JAC", modelo: "1040", anio_desde: "15", anio_hasta: "", grupo: ["49R - 1300"], categoria: "camion" },
  { marca: "JAC", modelo: "1131", anio_desde: "15", anio_hasta: "", grupo: ["49R - 1300"], categoria: "camion" },
  { marca: "JAC", modelo: "4253", anio_desde: "15", anio_hasta: "", grupo: ["4D - 1500"], categoria: "camion" },
  { marca: "JAC", modelo: "1061", anio_desde: "15", anio_hasta: "", grupo: ["27R - 1100"], cp: "27Q - 1200", categoria: "camion" },
  { marca: "JAC", modelo: "TODOS", anio_desde: "08", anio_hasta: "14", grupo: ["24 - 1150", "24 - 900"], categoria: "camion" },
  { marca: "KENWORTH", modelo: "TODOS", anio_desde: "00", anio_hasta: "10", grupo: ["31 - 1250"], categoria: "camion" },
  { marca: "MACK", modelo: "TODOS", anio_desde: "97", anio_hasta: "15", grupo: ["31 - 1250"], categoria: "camion" },
  { marca: "MERCEDES BENZ", modelo: "CAMION UTILITARIO / 711", anio_desde: "07", anio_hasta: "11", grupo: ["30H - 1250"], categoria: "camion" },
  { marca: "MERCEDES BENZ", modelo: "LS 2638", anio_desde: "05", anio_hasta: "08", grupo: ["31 - 1250"], categoria: "camion" },
  { marca: "MERCEDES BENZ", modelo: "LS 1634 / 2640", anio_desde: "05", anio_hasta: "09", grupo: ["4D - 1500"], categoria: "camion" },
  { marca: "MITSUBISHI", modelo: "CANTER", anio_desde: "92", anio_hasta: "10", grupo: ["27R - 1100"], cp: "27Q - 1200", categoria: "camion" },
  { marca: "MITSUBISHI", modelo: "CANTER (2 bat)", anio_desde: "11", anio_hasta: "15", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "camion" },
  { marca: "TOYOTA", modelo: "DYNA", anio_desde: "92", anio_hasta: "99", grupo: ["27R - 1100"], cp: "27Q - 1200", categoria: "camion" },
  { marca: "VOLVO", modelo: "VM", anio_desde: "05", anio_hasta: "10", grupo: ["30H - 1250"], cp: "27Q - 1200", categoria: "camion" },

  // ===================== AUTOMÓVILES (pág 4) =====================
  { marca: "AUDI", modelo: "A3 / A4 / A6 / A8 / Q7", anio_desde: "04", anio_hasta: "07", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "BMW", modelo: "X5 / X6 / X7 / 830I", anio_desde: "01", anio_hasta: "10", grupo: ["49R - 1300", "48R - 1200"], categoria: "auto" },
  { marca: "BMW", modelo: "116I / 135I / 318I / 525I / 530I / X3 / Z3 / Z4", anio_desde: "98", anio_hasta: "08", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "BUICK", modelo: "LE SABRE", anio_desde: "92", anio_hasta: "99", grupo: ["78 - 850"], categoria: "auto" },
  { marca: "CHANGAN", modelo: "BENNI", anio_desde: "22", anio_hasta: "", grupo: ["N40R - 700"], categoria: "auto" },
  { marca: "CHANGAN", modelo: "ALSVIN", anio_desde: "22", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },
  { marca: "CHANGAN", modelo: "CS15", anio_desde: "22", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },
  { marca: "CHANGAN", modelo: "CS55 PLUS", anio_desde: "22", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },
  { marca: "CHANGAN", modelo: "HUNTER (PICK UP)", anio_desde: "22", anio_hasta: "", grupo: ["24 - 1150", "24 - 850"], categoria: "auto" },
  { marca: "CHERY", modelo: "COW IN", anio_desde: "07", anio_hasta: "09", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "CHERY", modelo: "GRAND TIGGER", anio_desde: "13", anio_hasta: "17", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "CHERY", modelo: "GRAND TIGGO", anio_desde: "05", anio_hasta: "15", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "CHERY", modelo: "GRAND TIGGO", anio_desde: "16", anio_hasta: "", grupo: ["48R - 1200"], categoria: "auto" },
  { marca: "CHERY", modelo: "QQ", anio_desde: "06", anio_hasta: "12", grupo: ["45 - 750"], categoria: "auto" },
  { marca: "CHERY", modelo: "TIUNA X5", anio_desde: "13", anio_hasta: "18", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "CHERY", modelo: "TIGGO", anio_desde: "07", anio_hasta: "16", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "CHERY", modelo: "TIGGO 7 PRO", anio_desde: "22", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },
  { marca: "CHERY", modelo: "X1", anio_desde: "14", anio_hasta: "15", grupo: ["45 - 750"], categoria: "auto" },
  { marca: "CHERY", modelo: "ARAUCA", anio_desde: "12", anio_hasta: "16", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "CHERY", modelo: "ARAUCA", anio_desde: "18", anio_hasta: "", grupo: ["N40R - 700"], categoria: "auto" },
  { marca: "CHERY", modelo: "ORINOCO", anio_desde: "12", anio_hasta: "16", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CHEYENNE / SILVERADO", anio_desde: "92", anio_hasta: "99", grupo: ["43 - 950", "43 - 800"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CHEYENNE / SILVERADO", anio_desde: "00", anio_hasta: "07", grupo: ["78 - 850", "43 - 950"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CHEYENNE / SILVERADO", anio_desde: "08", anio_hasta: "15", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "CHEVROLET", modelo: "ASTRA", anio_desde: "02", anio_hasta: "06", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "AVALANCHE", anio_desde: "05", anio_hasta: "06", grupo: ["78 - 850", "34 - 1000"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "AVALANCHE", anio_desde: "07", anio_hasta: "08", grupo: ["34R - 1000"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "AVEO / BLAZER", anio_desde: "05", anio_hasta: "15", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CAMARO", anio_desde: "94", anio_hasta: "95", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CAPTIVA", anio_desde: "07", anio_hasta: "09", grupo: ["43 - 950", "43 - 800"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CAPRICE / CHEVI NOVA", anio_desde: "78", anio_hasta: "84", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CAVALIER", anio_desde: "92", anio_hasta: "94", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CENTURY / CELEBRITY", anio_desde: "83", anio_hasta: "96", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CHEVETTE", anio_desde: "81", anio_hasta: "96", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CHEVY", anio_desde: "08", anio_hasta: "11", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "COLORADO", anio_desde: "07", anio_hasta: "08", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CORSA", anio_desde: "96", anio_hasta: "06", grupo: ["43R - 800", "36R - 750"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "CORSICA", anio_desde: "90", anio_hasta: "96", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "EPICA", anio_desde: "07", anio_hasta: "09", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "ESTEEM", anio_desde: "97", anio_hasta: "02", grupo: ["45R - 850", "45R - 750"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "GRAND BLAZER", anio_desde: "92", anio_hasta: "01", grupo: ["43 - 950", "43 - 800"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "GRAND VITARA / XL7", anio_desde: "03", anio_hasta: "07", grupo: ["34 - 1000"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "CHEVROLET", modelo: "IMPALA", anio_desde: "00", anio_hasta: "05", grupo: ["78 - 850", "43 - 950"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "IMPALA SS", anio_desde: "07", anio_hasta: "08", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "JIMMY", anio_desde: "00", anio_hasta: "03", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "LUMINA", anio_desde: "96", anio_hasta: "99", grupo: ["78 - 850", "43 - 950"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "MONTECARLO", anio_desde: "90", anio_hasta: "", grupo: ["78 - 850", "34 - 1000"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "LUV/DMAX (4 CILINDROS)", anio_desde: "01", anio_hasta: "06", grupo: ["34R - 1000"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "CHEVROLET", modelo: "LUV/DMAX (6 CILINDROS)", anio_desde: "01", anio_hasta: "06", grupo: ["34R - 1000"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "CHEVROLET", modelo: "LUV-DMAX / LUV-DMAX GNV", anio_desde: "09", anio_hasta: "15", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "CHEVROLET", modelo: "MALIBU / MONTECARLO", anio_desde: "78", anio_hasta: "84", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "MONTANA / MERIVA", anio_desde: "90", anio_hasta: "08", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "MONZA", anio_desde: "90", anio_hasta: "07", grupo: ["43R - 800", "36R - 750"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "OPTRA ADVANCE", anio_desde: "04", anio_hasta: "07", grupo: ["34 - 1000", "22 - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "OPTRA DESING / HATCHBACK", anio_desde: "07", anio_hasta: "08", grupo: ["22 - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "OPTRA DESING", anio_desde: "09", anio_hasta: "11", grupo: ["34 - 1000", "22 - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "OPTRA LIMITED", anio_desde: "08", anio_hasta: "12", grupo: ["34 - 1000", "22 - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "ORLANDO / CRUZE", anio_desde: "13", anio_hasta: "15", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "SPARK", anio_desde: "06", anio_hasta: "15", grupo: ["N40R - 700"], categoria: "auto" },

  // ===================== AUTOMÓVILES (pág 5) =====================
  { marca: "CHEVROLET", modelo: "S 10 / SUNFIRE", anio_desde: "90", anio_hasta: "99", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "SUPER CARRY", anio_desde: "93", anio_hasta: "02", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "SWIFT", anio_desde: "92", anio_hasta: "97", grupo: ["45 - 750"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "TAHOE", anio_desde: "07", anio_hasta: "14", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "CHEVROLET", modelo: "TRAIL BLAZER", anio_desde: "02", anio_hasta: "08", grupo: ["78 - 850", "43 - 950"], categoria: "auto" },
  { marca: "CHEVROLET", modelo: "VITARA / WAGON R", anio_desde: "93", anio_hasta: "99", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "300 C", anio_desde: "07", anio_hasta: "08", grupo: ["49R - 1300", "48R - 1200"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "300M", anio_desde: "98", anio_hasta: "01", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "BRISA", anio_desde: "02", anio_hasta: "07", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "DODGE CALIBER", anio_desde: "07", anio_hasta: "12", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "CARAVAN", anio_desde: "97", anio_hasta: "00", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "DAKOTA", anio_desde: "07", anio_hasta: "08", grupo: ["65 - 1100"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "DODGE FORZA", anio_desde: "13", anio_hasta: "15", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "DODGE DART", anio_desde: "70", anio_hasta: "80", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "GRAND CARAVAN / INTREPID / LE BARON", anio_desde: "97", anio_hasta: "03", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "JOURNEY", anio_desde: "09", anio_hasta: "19", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "NEON", anio_desde: "97", anio_hasta: "99", grupo: ["59 - 850"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "NEON", anio_desde: "00", anio_hasta: "07", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "PT CRUISER", anio_desde: "02", anio_hasta: "08", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "DODGE RAM", anio_desde: "83", anio_hasta: "06", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "RAM 2500", anio_desde: "97", anio_hasta: "00", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "RAM 2500", anio_desde: "00", anio_hasta: "09", grupo: ["65 - 1100"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "STRATUS", anio_desde: "97", anio_hasta: "98", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "SEBRING", anio_desde: "97", anio_hasta: "09", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "CHRYSLER", modelo: "SPIRIT STEALTH", anio_desde: "91", anio_hasta: "95", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "CITROEN", modelo: "C3 / C4", anio_desde: "01", anio_hasta: "10", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "DAEWOO", modelo: "CIELO / ESPERO", anio_desde: "95", anio_hasta: "01", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "DAEWOO", modelo: "DAMAS", anio_desde: "97", anio_hasta: "02", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },
  { marca: "DAEWOO", modelo: "LANOS / LEGANZA / NUBIRA", anio_desde: "98", anio_hasta: "02", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "DAEWOO", modelo: "MATIZ", anio_desde: "99", anio_hasta: "01", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },
  { marca: "DAEWOO", modelo: "PRINCE / SALON", anio_desde: "93", anio_hasta: "98", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "DAEWOO", modelo: "RACER", anio_desde: "93", anio_hasta: "97", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "DAEWOO", modelo: "TACUMA", anio_desde: "01", anio_hasta: "02", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "DAEWOO", modelo: "TICO", anio_desde: "97", anio_hasta: "99", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },
  { marca: "DONGFENG", modelo: "ZNA", anio_desde: "14", anio_hasta: "16", grupo: ["34 - 1000", "22R - 850"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "DONGFENG", modelo: "RICH", anio_desde: "10", anio_hasta: "16", grupo: ["34 - 1000"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "DONGFENG", modelo: "HAIMA 7", anio_desde: "13", anio_hasta: "14", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "DONGFENG", modelo: "S30", anio_desde: "12", anio_hasta: "13", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "FIAT", modelo: "COUPE / FIORINO IDEA / MAREA", anio_desde: "95", anio_hasta: "10", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "FIAT", modelo: "STRADA / PUNTO", anio_desde: "90", anio_hasta: "10", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "FIAT", modelo: "PALIO / PALIO ADVENTURE / SIENA", anio_desde: "90", anio_hasta: "14", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "FIAT", modelo: "147 / SPAZIO / TUCAN", anio_desde: "86", anio_hasta: "89", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "FIAT", modelo: "PREMIO / UNO / TEMPRA", anio_desde: "86", anio_hasta: "91", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "FIAT", modelo: "REGATA", anio_desde: "84", anio_hasta: "90", grupo: ["36R - 750", "42R - 850"], categoria: "auto" },
  { marca: "FIAT", modelo: "RITMO", anio_desde: "85", anio_hasta: "90", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "FIAT", modelo: "ARGO TRECKING / MOBI TRECKING", anio_desde: "24", anio_hasta: "", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "FIAT", modelo: "CRONOS", anio_desde: "24", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },
  { marca: "FORD", modelo: "FIESTA / KA / ECOSPORT", anio_desde: "07", anio_hasta: "14", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "FORD", modelo: "CONTINENTAL / FAIRLINE", anio_desde: "63", anio_hasta: "75", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "FORD", modelo: "FAYRMONT / GALAXIE", anio_desde: "63", anio_hasta: "75", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "FORD", modelo: "ESCORT / ORION / DEL REY / CORCEL", anio_desde: "81", anio_hasta: "14", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "FORD", modelo: "FUSION", anio_desde: "07", anio_hasta: "14", grupo: ["42R - 850"], categoria: "auto" },
  { marca: "FORD", modelo: "FOCUS", anio_desde: "06", anio_hasta: "12", grupo: ["43R - 800", "36R - 750"], categoria: "auto" },
  { marca: "FORD", modelo: "ECOSPORT TITANIUM / FIESTA TITANIUM", anio_desde: "15", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },
  { marca: "FORD", modelo: "FX4", anio_desde: "06", anio_hasta: "14", grupo: ["65 - 1100"], categoria: "auto" },
  { marca: "FORD", modelo: "EXPLORER", anio_desde: "95", anio_hasta: "99", grupo: ["43 - 950", "43 - 800"], categoria: "auto" },

  // ===================== AUTOMÓVILES (pág 6) =====================
  { marca: "FORD", modelo: "EXPLORER", anio_desde: "00", anio_hasta: "05", grupo: ["59 - 850"], categoria: "auto" },
  { marca: "FORD", modelo: "EXPLORER / SPORT TRACK", anio_desde: "22", anio_hasta: "", grupo: ["65 - 1100"], categoria: "auto" },
  { marca: "FORD", modelo: "F-150 / FORTALEZA", anio_desde: "06", anio_hasta: "15", grupo: ["59 - 850"], categoria: "auto" },
  { marca: "FORD", modelo: "FESTIVA", anio_desde: "82", anio_hasta: "00", grupo: ["22R - 850", "36R - 750"], categoria: "auto" },
  { marca: "FORD", modelo: "LTD / MAVERIC / MUSTANG / ZEPHYR", anio_desde: "82", anio_hasta: "00", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "FORD", modelo: "SIERRA", anio_desde: "63", anio_hasta: "81", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "FORD", modelo: "RANGER / SCAPE", anio_desde: "88", anio_hasta: "94", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "FORD", modelo: "COUGAR", anio_desde: "80", anio_hasta: "85", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "FORD", modelo: "GRANADA / MUSTANG / LASER", anio_desde: "96", anio_hasta: "04", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "FORD", modelo: "LASER", anio_desde: "80", anio_hasta: "85", grupo: ["22R - 850"], categoria: "auto" },
  { marca: "FORD", modelo: "MUSTANG / RANGER", anio_desde: "96", anio_hasta: "04", grupo: ["59 - 850"], categoria: "auto" },
  { marca: "FORD", modelo: "MUSTANG", anio_desde: "97", anio_hasta: "06", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "FORD", modelo: "TAURUS", anio_desde: "07", anio_hasta: "14", grupo: ["34R - 1000"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "FORD", modelo: "TRACER", anio_desde: "92", anio_hasta: "96", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "FORTHING", modelo: "M4 / TS EVO", anio_desde: "24", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },
  { marca: "GEELY", modelo: "CK3", anio_desde: "05", anio_hasta: "10", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "GREAT WALL", modelo: "DEER / HOOVER / SAFE", anio_desde: "06", anio_hasta: "09", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "HONDA", modelo: "ACCORD 4 CIL", anio_desde: "90", anio_hasta: "98", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "HONDA", modelo: "ACORD 4 CIL", anio_desde: "00", anio_hasta: "08", grupo: ["45R - 850", "45R - 750"], categoria: "auto" },
  { marca: "HONDA", modelo: "ACCORD 6 CIL", anio_desde: "00", anio_hasta: "08", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "HONDA", modelo: "CIVIC / CIVIC EMOTION / CR-V", anio_desde: "93", anio_hasta: "08", grupo: ["45R - 850", "45R - 750"], categoria: "auto" },
  { marca: "HONDA", modelo: "CIVIC EMOTION", anio_desde: "02", anio_hasta: "06", grupo: ["45 - 750", "45 - 750"], categoria: "auto" },
  { marca: "HONDA", modelo: "CIVIC EVOLUTION", anio_desde: "07", anio_hasta: "15", grupo: ["45R - 850", "45R - 750"], categoria: "auto" },
  { marca: "HONDA", modelo: "FIT", anio_desde: "07", anio_hasta: "09", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },
  { marca: "HONDA", modelo: "LEGEND", anio_desde: "97", anio_hasta: "09", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "HONDA", modelo: "ODYSSEY / PILOT / VIGOR", anio_desde: "00", anio_hasta: "08", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "HONDA", modelo: "PRELUDE", anio_desde: "92", anio_hasta: "96", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "HUMMER", modelo: "HUMMER H1 / H2", anio_desde: "94", anio_hasta: "07", grupo: ["78 - 850", "34 - 1000"], categoria: "auto" },
  { marca: "HUMMER", modelo: "HUMMER H3", anio_desde: "06", anio_hasta: "07", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "ACCENT / COUPE / MATRIX / GETZ", anio_desde: "97", anio_hasta: "10", grupo: ["22R - 850"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "ATOS", anio_desde: "06", anio_hasta: "08", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "ELANTRA", anio_desde: "92", anio_hasta: "01", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "ELANTRA", anio_desde: "02", anio_hasta: "13", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "EXCEL", anio_desde: "92", anio_hasta: "99", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "GALLOPER / H1", anio_desde: "97", anio_hasta: "01", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "GETZ GLS - GNV", anio_desde: "11", anio_hasta: "12", grupo: ["45R - 850", "45R - 750"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "H-100", anio_desde: "97", anio_hasta: "99", grupo: ["27R - 1100"], cp: "27Q - 1200", categoria: "auto" },
  { marca: "HYUNDAI", modelo: "MATRIX", anio_desde: "03", anio_hasta: "07", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "SANTA FE", anio_desde: "05", anio_hasta: "15", grupo: ["34 - 1000"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "HYUNDAI", modelo: "SANTA FE GOLD", anio_desde: "07", anio_hasta: "09", grupo: ["34 - 1000"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "HYUNDAI", modelo: "SONATA", anio_desde: "92", anio_hasta: "01", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "SONATA", anio_desde: "02", anio_hasta: "06", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "HYUNDAI", modelo: "TUCSON", anio_desde: "05", anio_hasta: "10", grupo: ["22R - 850", "34R - 1000"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "TUCSON 4X4 / ELANTRA", anio_desde: "24", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "KONA / ACCENT", anio_desde: "24", anio_hasta: "", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "HYUNDAI", modelo: "SANTA FE / SANTA CRUZ / ELANTRA SPORT", anio_desde: "24", anio_hasta: "", grupo: ["48R - 1200"], categoria: "auto" },
  { marca: "ISUZU", modelo: "AMIGO / RODEO", anio_desde: "92", anio_hasta: "99", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "ISUZU", modelo: "TROOPER", anio_desde: "92", anio_hasta: "99", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "ISUZU", modelo: "CARIBE 442", anio_desde: "83", anio_hasta: "93", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "JAC", modelo: "T9", anio_desde: "24", anio_hasta: "", grupo: ["27R - 1100"], categoria: "auto" },
  { marca: "JAC", modelo: "TEPUY", anio_desde: "24", anio_hasta: "", grupo: ["42R - 850"], categoria: "auto" },
  { marca: "JEEP", modelo: "CJ-5 / CJ-6 / CJ-7 / CJ-10", anio_desde: "74", anio_hasta: "90", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "JEEP", modelo: "COMANCHE / CHEROKEE", anio_desde: "80", anio_hasta: "01", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "JEEP", modelo: "COMMANDER", anio_desde: "07", anio_hasta: "10", grupo: ["34R - 1000"], categoria: "auto" },
  { marca: "JEEP", modelo: "COMPASS", anio_desde: "07", anio_hasta: "09", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "JEEP", modelo: "GRAND CHEROKEE", anio_desde: "95", anio_hasta: "98", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "JEEP", modelo: "GRAND CHEROKEE", anio_desde: "99", anio_hasta: "", grupo: ["43 - 950", "43 - 800"], categoria: "auto" },

  // ===================== AUTOMÓVILES (pág 7) =====================
  { marca: "JEEP", modelo: "GRAND CHEROKEE", anio_desde: "00", anio_hasta: "05", grupo: ["59 - 850"], categoria: "auto" },
  { marca: "JEEP", modelo: "GRAND CHEROKEE", anio_desde: "06", anio_hasta: "10", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "JEEP", modelo: "GRAND CHEROKEE", anio_desde: "11", anio_hasta: "17", grupo: ["49R - 1300", "48R - 1200"], categoria: "auto" },
  { marca: "JEEP", modelo: "GRAND WAGONEER", anio_desde: "79", anio_hasta: "94", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "JEEP", modelo: "LIBERTY", anio_desde: "02", anio_hasta: "03", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "JEEP", modelo: "LIBERTY / LIMITED / WRANGLER", anio_desde: "04", anio_hasta: "16", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "JEEP", modelo: "WAGONEER", anio_desde: "04", anio_hasta: "16", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "JEEP", modelo: "RENEGADE SPORT TURBO", anio_desde: "23", anio_hasta: "", grupo: ["48R - 1200"], categoria: "auto" },
  { marca: "JEEP", modelo: "RAM", anio_desde: "24", anio_hasta: "", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "JIM", modelo: "REMAX-S", anio_desde: "24", anio_hasta: "", grupo: ["27R - 1100"], categoria: "auto" },
  { marca: "JMC", modelo: "VIGUS PRO", anio_desde: "24", anio_hasta: "", grupo: ["30H - 1250"], categoria: "auto" },
  { marca: "KIA", modelo: "CARENS / RIO / SEPHIA", anio_desde: "00", anio_hasta: "03", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "KIA", modelo: "CERATO / SHUMA / SPECTRA", anio_desde: "00", anio_hasta: "03", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "KIA", modelo: "CARNIVAL / OPTIMA / PREGIO", anio_desde: "00", anio_hasta: "09", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "KIA", modelo: "PICANTO", anio_desde: "06", anio_hasta: "09", grupo: ["NS40R - 670", "N40R - 700"], categoria: "auto" },
  { marca: "KIA", modelo: "RIO STYLUS", anio_desde: "07", anio_hasta: "12", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "KIA", modelo: "SEDONA", anio_desde: "06", anio_hasta: "08", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "KIA", modelo: "SORENTO", anio_desde: "05", anio_hasta: "09", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "KIA", modelo: "SPORTAGE", anio_desde: "00", anio_hasta: "03", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "KIA", modelo: "SPORTAGE", anio_desde: "04", anio_hasta: "12", grupo: ["34R - 1000"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "LADA", modelo: "NIVA / MATRIUSKA", anio_desde: "92", anio_hasta: "96", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "LADA", modelo: "SAMARA", anio_desde: "92", anio_hasta: "96", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "LAND ROVER", modelo: "DEFENDER / RANGE ROVER", anio_desde: "75", anio_hasta: "17", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "LAND ROVER", modelo: "DEFENDER", anio_desde: "07", anio_hasta: "08", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "LEXUS", modelo: "300 / 400", anio_desde: "91", anio_hasta: "97", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "LIFAN", modelo: "520 TALENT", anio_desde: "08", anio_hasta: "09", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "LINCOLN", modelo: "NAVIGATOR", anio_desde: "06", anio_hasta: "10", grupo: ["65 - 1100"], categoria: "auto" },
  { marca: "LINCOLN", modelo: "LINCOLN TOWN CAR", anio_desde: "90", anio_hasta: "01", grupo: ["43 - 950", "43 - 800"], categoria: "auto" },
  { marca: "LINCOLN", modelo: "LINCOLN TOWN CAR", anio_desde: "06", anio_hasta: "10", grupo: ["43 - 950", "43 - 800"], categoria: "auto" },
  { marca: "MAZDA", modelo: "03 / 05 / 06 / 626 / 929", anio_desde: "05", anio_hasta: "09", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "MAZDA", modelo: "ALLEGRO / 323", anio_desde: "95", anio_hasta: "02", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "MAZDA", modelo: "B 2600 (PICK - UP) / BT 50 (PICK - UP)", anio_desde: "97", anio_hasta: "16", grupo: ["24 - 1150", "24 - 900"], categoria: "auto" },
  { marca: "MAZDA", modelo: "DEMIO", anio_desde: "04", anio_hasta: "08", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "MAZDA", modelo: "MIATA", anio_desde: "92", anio_hasta: "98", grupo: ["N40R - 700"], categoria: "auto" },
  { marca: "MAZDA", modelo: "MPV", anio_desde: "92", anio_hasta: "99", grupo: ["34 - 1000"], categoria: "auto" },
  { marca: "MERCEDES BENZ", modelo: "190E / 300E / A160 / A170", anio_desde: "91", anio_hasta: "08", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "MERCEDES BENZ", modelo: "C300", anio_desde: "93", anio_hasta: "15", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "MERCEDES BENZ", modelo: "E320", anio_desde: "91", anio_hasta: "16", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "MERCEDES BENZ", modelo: "S500", anio_desde: "91", anio_hasta: "16", grupo: ["49R - 1300", "48R - 1200"], categoria: "auto" },
  { marca: "MERCEDES BENZ", modelo: "500SEL / 600SEL / ML230", anio_desde: "91", anio_hasta: "16", grupo: ["43R - 950", "43R - 800"], categoria: "auto" },
  { marca: "MERCEDES BENZ", modelo: "300ML", anio_desde: "13", anio_hasta: "18", grupo: ["49R - 1300", "48R - 1200"], categoria: "auto" },
  { marca: "MERCEDES BENZ", modelo: "SPRINTER 313 - 413", anio_desde: "76", anio_hasta: "08", grupo: ["49R - 1300", "48R - 1200"], categoria: "auto" },
  { marca: "MINI", modelo: "COOPER", anio_desde: "05", anio_hasta: "10", grupo: ["36R - 750"], categoria: "auto" },
  { marca: "MITSUBISHI", modelo: "3000 / DIAMANTE / GALANT", anio_desde: "93", anio_hasta: "95", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "MITSUBISHI", modelo: "COLT / ECLIPSE / EXPO", anio_desde: "93", anio_hasta: "95", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "MITSUBISHI", modelo: "GRANDIS", anio_desde: "03", anio_hasta: "11", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
  { marca: "MITSUBISHI", modelo: "MF / MX / ZX", anio_desde: "93", anio_hasta: "95", grupo: ["22 - 850", "42 - 850"], categoria: "auto" },
  { marca: "MITSUBISHI", modelo: "MX / MF", anio_desde: "98", anio_hasta: "01", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "MITSUBISHI", modelo: "PANEL (L300) / VAN", anio_desde: "93", anio_hasta: "95", grupo: ["45 - 750"], categoria: "auto" },
  { marca: "MITSUBISHI", modelo: "LANCER / SIGNO", anio_desde: "93", anio_hasta: "15", grupo: ["22R - 850", "42R - 850"], categoria: "auto" },
  { marca: "MITSUBISHI", modelo: "SPACE WAGON / MIRAGE", anio_desde: "98", anio_hasta: "01", grupo: ["45R - 850", "45R - 750"], categoria: "auto" },
  { marca: "MITSUBISHI", modelo: "MONTERO SPORT / MONTERO LIMITED", anio_desde: "93", anio_hasta: "16", grupo: ["24R - 1150", "24R - 900"], cp: "24Q - 1150", categoria: "auto" },
];
